In [2]:
import numpy as np

# Load the .npy file
data = np.load('Detections.npy')

# Print the loaded data
print(data)

[[[511 108]
  [507 108]
  [506 108]
  ...
  [ 13 322]
  [ 13 324]
  [ 14 325]]

 [[116 293]
  [119 294]
  [121 295]
  ...
  [423 278]
  [425 282]
  [427 285]]

 [[460 286]
  [460 288]
  [461 291]
  ...
  [428  17]
  [424  17]
  [421  16]]

 ...

 [[157  33]
  [158  35]
  [160  37]
  ...
  [152 459]
  [149 460]
  [146 460]]

 [[  0   2]
  [  1   3]
  [  1   5]
  ...
  [ 63 433]
  [ 60 432]
  [ 57 431]]

 [[406  46]
  [407  48]
  [409  51]
  ...
  [491 147]
  [491 151]
  [491 155]]]
